// <auto-generated />
namespace OnTarget.Channel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateChannelEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateChannelEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111027185_CreateChannelEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
